#include <string>
extern const std::string src_accelerate_cl;
extern const std::string src_advec_cell_cl;
extern const std::string src_advec_mom_cl;
extern const std::string src_calc_dt_cl;
extern const std::string src_field_summary_cl;
extern const std::string src_flux_calc_cl;
extern const std::string src_generate_chunk_cl;
extern const std::string src_halo_bare_cl;
extern const std::string src_ideal_gas_cl;
extern const std::string src_initialise_chunk_cl;
extern const std::string src_macros_cl;
extern const std::string src_PdV_cl;
extern const std::string src_reduction_cl;
extern const std::string src_reset_field_cl;
extern const std::string src_revert_cl;
extern const std::string src_set_field_cl;
extern const std::string src_update_halo_cl;
extern const std::string src_viscosity_cl;
